

sales_city_2021 <- dbGetQuery(con2,"
WITH CLI AS (SELECT C.CLICODIGO,CIDADE,SETOR FROM CLIEN C
LEFT JOIN (SELECT CLICODIGO,CIDNOME CIDADE, ZODESCRICAO SETOR FROM ENDCLI E
           LEFT JOIN CIDADE CD ON E.CIDCODIGO=CD.CIDCODIGO
           INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA 
                       WHERE ZOCODIGO IN(20,21,22,23,24,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
           WHERE ENDFAT='S'
) ED ON C.CLICODIGO=ED.CLICODIGO
WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,CIDADE FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDSITPED<>'C' AND PEDDTBAIXA BETWEEN '01.01.2021' AND '31.12.2021'),
     
AUX AS (SELECT PROCODIGO,PROTIPO FROM PRODU)     

SELECT 
 PEDDTBAIXA,
  P.CIDADE,
   SUM(PDPQTDADE) QTD,
    SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA  
     FROM PDPRD PD
      INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
       INNER JOIN AUX ON PD.PROCODIGO= AUX.PROCODIGO
        GROUP BY 1,2") 

save(sales_city_2021,file="C:/Users/Repro/Documents/R/ADM/REPORTS_AUTO/BASES/sales_city_2021.RData")
