
## RANKING DE CLIENTES
## 05.2022
## SANDRO JAKOSKA

## LIBRARIES =======================================================================

library(tidyverse)
library(lubridate)
library(reshape2)
library(DBI)
library(googlesheets4)

## DB CONNECTION ====================================================================

con2 <- dbConnect(odbc::odbc(), "reproreplica")


gespar <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  CLI AS (SELECT C.CLICODIGO,SETOR FROM CLIEN C
  LEFT JOIN (SELECT CLICODIGO, ZODESCRICAO SETOR FROM ENDCLI E
  INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN(20,21,22,23,24,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
  WHERE ENDFAT='S'
  ) ED ON C.CLICODIGO=ED.CLICODIGO
  WHERE CLICLIENTE='S'),
  
  
  PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO,SETOR FROM PEDID P
  INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
   INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
    WHERE PEDDTBAIXA BETWEEN '01.05.2022' AND 'TODAY' AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),
     
     VARILUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57 AND PROTIPO<>'T'),
      
      KODAK AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (24,93) AND PROTIPO<>'T'),
       
       CRIZAL AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%CRIZAL%' AND PROTIPO='T' AND PROSITUACAO='A'),
            
        CRIZALVS AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%CRIZAL%' AND PROTIPO<>'T' AND PROSITUACAO='A'),      
      
         MREPRO AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (106,128,135,158,159,189) AND PROTIPO<>'T'),
          
          TRANSITIONS AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%TGEN8%' AND PROSITUACAO='A') 
           
            TRANSITIONS AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%TGEN8%' AND PROSITUACAO='A') 
  
  SELECT PD.ID_PEDIDO,
            PEDDTBAIXA,
             CLICODIGO,
              SETOR,
               PD.PROCODIGO,
                PDPDESCRICAO,
                 CASE 
                  WHEN VLX.PROCODIGO IS NOT NULL THEN 'VARILUX'
                   WHEN KDK.PROCODIGO IS NOT NULL THEN 'KODAK'
                    WHEN CZL.PROCODIGO IS NOT NULL THEN 'CRIZAL'
                     WHEN CZL.PROCODIGO IS NOT NULL THEN 'CRIZAL VS'
                      WHEN MRP.PROCODIGO IS NOT NULL THEN 'MARCAS REPRO'
                     ELSE NULL END CATEGORIA,
                       IIF(TRS.PROCODIGO IS NOT NULL, 1,0) TRANSITIONS,
                 SUM(PDPQTDADE) QTD,
                 SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD PD
    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
     LEFT JOIN VARILUX VLX ON VLX.PROCODIGO=PD.PROCODIGO
      LEFT JOIN KODAK KDK ON KDK.PROCODIGO=PD.PROCODIGO
       LEFT JOIN CRIZAL CZL ON CZL.PROCODIGO=PD.PROCODIGO
        LEFT JOIN CRIZALVS CVS ON CVS.PROCODIGO=PD.PROCODIGO
         LEFT JOIN MREPRO MRP ON MRP.PROCODIGO=PD.PROCODIGO
          LEFT JOIN TRANSITIONS TRS ON TRS.PROCODIGO=PD.PROCODIGO
  GROUP BY 1,2,3,4,5,6,7,8
  ")  

View(gespar)
