
## RANKING DE CLIENTES
## 05.2022
## SANDRO JAKOSKA

## LIBRARIES =======================================================================

library(tidyverse)
library(lubridate)
library(reshape2)
library(DBI)
library(googlesheets4)

library(gmailr)

## DB CONNECTION ====================================================================

con2 <- dbConnect(odbc::odbc(), "reproreplica")




gespar <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  CLI AS (SELECT C.CLICODIGO,SETOR FROM CLIEN C
  LEFT JOIN (SELECT CLICODIGO, ZODESCRICAO SETOR FROM ENDCLI E
  INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN(20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
  WHERE ENDFAT='S'
  ) ED ON C.CLICODIGO=ED.CLICODIGO
  WHERE CLICLIENTE='S'),
  
  
  PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO,SETOR,TPCODIGO FROM PEDID P
  INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
   LEFT JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
    WHERE (PEDDTBAIXA BETWEEN '01.01.2022' AND '31.10.2022' OR
           PEDDTBAIXA BETWEEN '01.01.2021' AND '31.10.2021')
    
    AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),
     
     VARILUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57 AND PROTIPO<>'T'),
      
      KODAK AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (24,93) AND PROTIPO<>'T'),
       
       CRIZAL AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%CRIZAL%' AND PROTIPO='T'),
            
        CRIZALVS AS (SELECT PROCODIGO FROM PRODU WHERE (PRODESCRICAO LIKE '%CRIZAL%' OR PRODESCRICAO LIKE '%C.FORTE%')  AND GR1CODIGO=2),      
      
         MREPRO AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (106,128,135,158,159,189) AND PROTIPO<>'T'),
          
          TRANSITIONS AS (SELECT PROCODIGO FROM PRODU 
           WHERE (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%') ), 
           
            LENTES AS (SELECT PROCODIGO FROM PRODU 
           WHERE PROTIPO IN ('F','P','E') ) 
  
  SELECT   PEDDTBAIXA DATA,
            EXTRACT(MONTH FROM PEDDTBAIXA) MES,
             EXTRACT(YEAR FROM PEDDTBAIXA) ANO,
              IIF(TPCODIGO IN (1,6,11), 1,0) ATC,
               CLICODIGO,
                SETOR,
                 PD.PROCODIGO,
                  PDPDESCRICAO,
                   CASE 
                    WHEN VLX.PROCODIGO IS NOT NULL THEN 'VARILUX'
                     WHEN KDK.PROCODIGO IS NOT NULL THEN 'KODAK'
                      WHEN CZL.PROCODIGO IS NOT NULL THEN 'CRIZAL'
                       WHEN CVS.PROCODIGO IS NOT NULL THEN 'CRIZAL VS'
                        WHEN MRP.PROCODIGO IS NOT NULL THEN 'MARCAS REPRO'
                         ELSE 'OUTROS' END CATEGORIA,
                          IIF(TRS.PROCODIGO IS NOT NULL, 1,0) TRANSITIONS,
                           IIF(LNT.PROCODIGO IS NOT NULL, 1,0) LENTES,
                            SUM(PDPQTDADE) QTD,
                             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD PD
    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
     LEFT JOIN VARILUX VLX ON VLX.PROCODIGO=PD.PROCODIGO
      LEFT JOIN KODAK KDK ON KDK.PROCODIGO=PD.PROCODIGO
       LEFT JOIN CRIZAL CZL ON CZL.PROCODIGO=PD.PROCODIGO
        LEFT JOIN CRIZALVS CVS ON CVS.PROCODIGO=PD.PROCODIGO
         LEFT JOIN MREPRO MRP ON MRP.PROCODIGO=PD.PROCODIGO
          LEFT JOIN TRANSITIONS TRS ON TRS.PROCODIGO=PD.PROCODIGO
           LEFT JOIN LENTES LNT ON LNT.PROCODIGO=PD.PROCODIGO
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11
  ")  

View(gespar)

gespar2 <- gespar %>% group_by(MES,ANO,ATC,CATEGORIA,TRANSITIONS,LENTES) %>% 
  summarize(QTD=sum(QTD),VRVENDA=sum(VRVENDA)) %>% as.data.frame() %>% mutate(CATEGORIA=trimws(CATEGORIA))

View(gespar2)

write_sheet("1hvhB0Gv2q4aWfg_A_GEreQ6joD8PtdRaroDzB9yq39Q",data =gespar2,sheet = "DADOS")


## VOUCHERS

gespar_voucher <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISCODIGO IN ('5.91V','6.91V')),
  
  CLI AS (SELECT C.CLICODIGO,SETOR FROM CLIEN C
  LEFT JOIN (SELECT CLICODIGO, ZODESCRICAO SETOR FROM ENDCLI E
  INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
  WHERE ENDFAT='S'
  ) ED ON C.CLICODIGO=ED.CLICODIGO
  WHERE CLICLIENTE='S'),
  
  
  PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO,SETOR,TPCODIGO FROM PEDID P
  INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
   LEFT JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
    WHERE (PEDDTBAIXA BETWEEN '01.01.2022' AND '31.10.2022' OR
           PEDDTBAIXA BETWEEN '01.01.2021' AND '31.10.2021')
    
    AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),
     
     VARILUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57 AND PROTIPO<>'T'),
      
      KODAK AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (24,93) AND PROTIPO<>'T'),
       
       CRIZAL AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%CRIZAL%' AND PROTIPO='T'),
            
        CRIZALVS AS (SELECT PROCODIGO FROM PRODU WHERE (PRODESCRICAO LIKE '%CRIZAL%' OR PRODESCRICAO LIKE '%C.FORTE%')  AND GR1CODIGO=2),      
      
         MREPRO AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (106,128,135,158,159,189) AND PROTIPO<>'T'),
          
          TRANSITIONS AS (SELECT PROCODIGO FROM PRODU 
           WHERE (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%') ), 
           
            LENTES AS (SELECT PROCODIGO FROM PRODU 
           WHERE PROTIPO IN ('F','P','E') ) 
  
  SELECT   PEDDTBAIXA DATA,
            EXTRACT(MONTH FROM PEDDTBAIXA) MES,
             EXTRACT(YEAR FROM PEDDTBAIXA) ANO,
              IIF(TPCODIGO IN (1,6,11), 1,0) ATC,
               CLICODIGO,
                SETOR,
                 PD.PROCODIGO,
                  PDPDESCRICAO,
                   CASE 
                    WHEN VLX.PROCODIGO IS NOT NULL THEN 'VARILUX'
                     WHEN KDK.PROCODIGO IS NOT NULL THEN 'KODAK'
                      WHEN CZL.PROCODIGO IS NOT NULL THEN 'CRIZAL'
                       WHEN CVS.PROCODIGO IS NOT NULL THEN 'CRIZAL VS'
                        WHEN MRP.PROCODIGO IS NOT NULL THEN 'MARCAS REPRO'
                         ELSE 'OUTROS' END CATEGORIA,
                          IIF(TRS.PROCODIGO IS NOT NULL, 1,0) TRANSITIONS,
                           IIF(LNT.PROCODIGO IS NOT NULL, 1,0) LENTES,
                            SUM(PDPQTDADE) QTD,
                             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD PD
    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
     LEFT JOIN VARILUX VLX ON VLX.PROCODIGO=PD.PROCODIGO
      LEFT JOIN KODAK KDK ON KDK.PROCODIGO=PD.PROCODIGO
       LEFT JOIN CRIZAL CZL ON CZL.PROCODIGO=PD.PROCODIGO
        LEFT JOIN CRIZALVS CVS ON CVS.PROCODIGO=PD.PROCODIGO
         LEFT JOIN MREPRO MRP ON MRP.PROCODIGO=PD.PROCODIGO
          LEFT JOIN TRANSITIONS TRS ON TRS.PROCODIGO=PD.PROCODIGO
           LEFT JOIN LENTES LNT ON LNT.PROCODIGO=PD.PROCODIGO
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11
  ")  

View(gespar_voucher)

gespar_voucher2 <- gespar_voucher %>% group_by(MES,ANO,ATC,CATEGORIA,TRANSITIONS,LENTES) %>% 
  summarize(QTD=sum(QTD),VRVENDA=sum(VRVENDA)) %>% as.data.frame() %>% mutate(CATEGORIA=trimws(CATEGORIA))

View(gespar_voucher2)

write_sheet("1hvhB0Gv2q4aWfg_A_GEreQ6joD8PtdRaroDzB9yq39Q",data =gespar_voucher2,sheet = "VOUCHERS")

##  SEM MONDADORI E MASTER ====================================================================


gespar_mm <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  CLI AS (SELECT C.CLICODIGO,GCLCODIGO,SETOR FROM CLIEN C
  LEFT JOIN (SELECT CLICODIGO, ZODESCRICAO SETOR FROM ENDCLI E
  INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN(20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
  WHERE ENDFAT='S'
  ) ED ON C.CLICODIGO=ED.CLICODIGO
  WHERE CLICLIENTE='S' ),
  
  
  PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO,GCLCODIGO,SETOR,TPCODIGO FROM PEDID P
  INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
   LEFT JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
    WHERE (PEDDTBAIXA BETWEEN '01.01.2022' AND '31.10.2022' OR
           PEDDTBAIXA BETWEEN '01.01.2021' AND '31.10.2021')
    
    AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N') AND
    P.CLICODIGO NOT IN (SELECT CLICODIGO FROM CLIEN WHERE GCLCODIGO IN (129,299))),
     
     VARILUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57 AND PROTIPO<>'T'),
      
      KODAK AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (24,93) AND PROTIPO<>'T'),
       
       CRIZAL AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%CRIZAL%' AND PROTIPO='T' ),
            
        CRIZALVS AS (SELECT PROCODIGO FROM PRODU WHERE (PRODESCRICAO LIKE '%CRIZAL%' OR PRODESCRICAO LIKE '%C.FORTE%')  AND GR1CODIGO=2 ),      
      
         MREPRO AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (106,128,135,158,159,189) AND PROTIPO<>'T'),
          
          TRANSITIONS AS (SELECT PROCODIGO FROM PRODU 
           WHERE (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%') ), 
           
            LENTES AS (SELECT PROCODIGO FROM PRODU 
           WHERE PROTIPO IN ('F','P','E') AND PROSITUACAO='A') 
  
  SELECT   PEDDTBAIXA DATA,
            EXTRACT(MONTH FROM PEDDTBAIXA) MES,
             EXTRACT(YEAR FROM PEDDTBAIXA) ANO,
              IIF(TPCODIGO IN (1,6,11), 1,0) ATC,
               CLICODIGO,
                GCLCODIGO,
                 SETOR,
                  PD.PROCODIGO,
                   PDPDESCRICAO,
                    CASE 
                    WHEN VLX.PROCODIGO IS NOT NULL THEN 'VARILUX'
                     WHEN KDK.PROCODIGO IS NOT NULL THEN 'KODAK'
                      WHEN CZL.PROCODIGO IS NOT NULL THEN 'CRIZAL'
                       WHEN CVS.PROCODIGO IS NOT NULL THEN 'CRIZAL VS'
                        WHEN MRP.PROCODIGO IS NOT NULL THEN 'MARCAS REPRO'
                         ELSE 'OUTROS' END CATEGORIA,
                          IIF(TRS.PROCODIGO IS NOT NULL, 1,0) TRANSITIONS,
                           IIF(LNT.PROCODIGO IS NOT NULL, 1,0) LENTES,
                            SUM(PDPQTDADE) QTD,
                             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD PD
    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
     LEFT JOIN VARILUX VLX ON VLX.PROCODIGO=PD.PROCODIGO
      LEFT JOIN KODAK KDK ON KDK.PROCODIGO=PD.PROCODIGO
       LEFT JOIN CRIZAL CZL ON CZL.PROCODIGO=PD.PROCODIGO
        LEFT JOIN CRIZALVS CVS ON CVS.PROCODIGO=PD.PROCODIGO
         LEFT JOIN MREPRO MRP ON MRP.PROCODIGO=PD.PROCODIGO
          LEFT JOIN TRANSITIONS TRS ON TRS.PROCODIGO=PD.PROCODIGO
           LEFT JOIN LENTES LNT ON LNT.PROCODIGO=PD.PROCODIGO
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
  ")  

View(gespar_mm)

gespar_mm2 <- gespar_mm %>% group_by(MES,ANO,ATC,CATEGORIA,TRANSITIONS,LENTES) %>% 
  summarize(QTD=sum(QTD),VRVENDA=sum(VRVENDA)) %>% as.data.frame() %>% mutate(CATEGORIA=trimws(CATEGORIA))

View(gespar_mm2)

write_sheet("1CU8-HaSUMIIg6vv2MWJOHMm5DBnt5-G4rL8eVi_3NuU",data =gespar_mm2,sheet = "DADOS")


## VOUCHERS

gespar_mm_voucher <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISCODIGO IN ('5.91V','6.91V')),
  
   CLI AS (SELECT C.CLICODIGO,GCLCODIGO,SETOR FROM CLIEN C
  LEFT JOIN (SELECT CLICODIGO, ZODESCRICAO SETOR FROM ENDCLI E
  INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN(20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
  WHERE ENDFAT='S'
  ) ED ON C.CLICODIGO=ED.CLICODIGO
  WHERE CLICLIENTE='S' ),
  
  
  PED AS (SELECT ID_PEDIDO,PEDDTBAIXA,P.CLICODIGO,GCLCODIGO,SETOR,TPCODIGO FROM PEDID P
  INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
   LEFT JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
    WHERE (PEDDTBAIXA BETWEEN '01.01.2022' AND '31.10.2022' OR
           PEDDTBAIXA BETWEEN '01.01.2021' AND '31.10.2021')
    
    AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N') AND
    P.CLICODIGO NOT IN (SELECT CLICODIGO FROM CLIEN WHERE GCLCODIGO IN (129,299))),
     
     
     VARILUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57 AND PROTIPO<>'T'),
      
      KODAK AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (24,93) AND PROTIPO<>'T'),
       
       CRIZAL AS (SELECT PROCODIGO FROM PRODU 
           WHERE PRODESCRICAO LIKE '%CRIZAL%' AND PROTIPO='T' ),
            
        CRIZALVS AS (SELECT PROCODIGO FROM PRODU WHERE (PRODESCRICAO LIKE '%CRIZAL%' OR PRODESCRICAO LIKE '%C.FORTE%')  AND GR1CODIGO=2),      
      
         MREPRO AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (106,128,135,158,159,189) AND PROTIPO<>'T'),
          
          TRANSITIONS AS (SELECT PROCODIGO FROM PRODU 
           WHERE (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%') ), 
           
            LENTES AS (SELECT PROCODIGO FROM PRODU 
           WHERE PROTIPO IN ('F','P','E')) 
  
  SELECT   PEDDTBAIXA DATA,
            EXTRACT(MONTH FROM PEDDTBAIXA) MES,
             EXTRACT(YEAR FROM PEDDTBAIXA) ANO,
              IIF(TPCODIGO IN (1,6,11), 1,0) ATC,
               CLICODIGO,
                SETOR,
                 PD.PROCODIGO,
                  PDPDESCRICAO,
                   CASE 
                    WHEN VLX.PROCODIGO IS NOT NULL THEN 'VARILUX'
                     WHEN KDK.PROCODIGO IS NOT NULL THEN 'KODAK'
                      WHEN CZL.PROCODIGO IS NOT NULL THEN 'CRIZAL'
                       WHEN CVS.PROCODIGO IS NOT NULL THEN 'CRIZAL VS'
                        WHEN MRP.PROCODIGO IS NOT NULL THEN 'MARCAS REPRO'
                         ELSE 'OUTROS' END CATEGORIA,
                          IIF(TRS.PROCODIGO IS NOT NULL, 1,0) TRANSITIONS,
                           IIF(LNT.PROCODIGO IS NOT NULL, 1,0) LENTES,
                            SUM(PDPQTDADE) QTD,
                             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD PD
    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
     LEFT JOIN VARILUX VLX ON VLX.PROCODIGO=PD.PROCODIGO
      LEFT JOIN KODAK KDK ON KDK.PROCODIGO=PD.PROCODIGO
       LEFT JOIN CRIZAL CZL ON CZL.PROCODIGO=PD.PROCODIGO
        LEFT JOIN CRIZALVS CVS ON CVS.PROCODIGO=PD.PROCODIGO
         LEFT JOIN MREPRO MRP ON MRP.PROCODIGO=PD.PROCODIGO
          LEFT JOIN TRANSITIONS TRS ON TRS.PROCODIGO=PD.PROCODIGO
           LEFT JOIN LENTES LNT ON LNT.PROCODIGO=PD.PROCODIGO
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11
  ")  

View(gespar_mm_voucher)

gespar_mm_voucher2 <- gespar_mm_voucher %>% group_by(MES,ANO,ATC,CATEGORIA,TRANSITIONS,LENTES) %>% 
  summarize(QTD=sum(QTD),VRVENDA=sum(VRVENDA)) %>% as.data.frame() %>% mutate(CATEGORIA=trimws(CATEGORIA))

View(gespar_mm_voucher2)

write_sheet("1CU8-HaSUMIIg6vv2MWJOHMm5DBnt5-G4rL8eVi_3NuU",data =gespar_mm_voucher2,sheet = "VOUCHERS")


## SEND MAIL ====================================================================


gm_auth_configure(path = "C:\\Users\\Repro\\Documents\\R\\ADM\\REPORTS_AUTO\\sendmail.json")

mymail <- gm_mime() %>% 
  gm_to("sandro.jakoska@repro.com.br,cristiano.regis@repro.com.br") %>% 
  gm_from ("comunicacao@repro.com.br") %>%
  gm_subject("RELATORIO GESPAR") %>%
  gm_text_body("RELATÓRIO ATUALIZADO.

GESPAR:  
ACESSE O LINK https://docs.google.com/spreadsheets/d/1hvhB0Gv2q4aWfg_A_GEreQ6joD8PtdRaroDzB9yq39Q/edit?usp=sharing.

GESPAR2:
ACESSE O LINK https://docs.google.com/spreadsheets/d/1CU8-HaSUMIIg6vv2MWJOHMm5DBnt5-G4rL8eVi_3NuU/edit?usp=sharing.

ESSE É UM EMAIL AUTOMÁTICO.") 
gm_send_message(mymail)


