## NETSALES
## SANDRO JAKOSKA


library(DBI)
library(dplyr)
library(googlesheets4)

con2 <- dbConnect(odbc::odbc(), "reproreplica")


pctsaldo <- dbGetQuery(con2,"
WITH SETOR AS (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA),

ENDE AS (SELECT CLICODIGO, ZODESCRICAO FROM ENDCLI INNER JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),

CLI AS (SELECT  CLIEN.CLICODIGO,CLIRAZSOCIAL,ZODESCRICAO FROM CLIEN LEFT JOIN ENDE ON CLIEN.CLICODIGO=ENDE.CLICODIGO ),

PROD AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU),

CLIPCT AS (SELECT PCTCLI.CLICODIGO,CLIRAZSOCIAL,ZODESCRICAO SETOR_COMERCIAL,PCTNUMERO,PCTDTCAD,PCTDTFIM,PCTDTSUSP,PCTOBSER,PCTSUSPOBS FROM PCTCLI
           LEFT JOIN CLI ON PCTCLI.CLICODIGO=CLI.CLICODIGO WHERE PCTSITUACAO<>'C')

SELECT CLICODIGO,CLIRAZSOCIAL RAZAO_SOCIAL,SETOR_COMERCIAL, 
PCTPRO.PCTNUMERO,PCTDTCAD PCT_DATA_CADASTRO,PCTDTFIM TERMINO,PCTPRO.PROCODIGO,
PRODESCRICAO DESCRICAO,CAST (PCPPCOUNIT AS NUMERIC(15,5)) PRECO_UNIT,PCPQTDADE QTD,PCPSALDO SALDO_ATUAL,
PCTDTSUSP DATA_SUSPENSAO,CAST(PCTOBSER AS VARCHAR(500)) OBS,PCTSUSPOBS
FROM PCTPRO 
INNER JOIN CLIPCT ON PCTPRO.PCTNUMERO=CLIPCT.PCTNUMERO
LEFT JOIN PROD ON PCTPRO.PROCODIGO=PROD.PROCODIGO")

range_write("1gVJ6MypZLYVSS_dv-HJZmNsHzf0MNID4ufNYT7KrsWk",
            sheet = "DADOS",data = pctsaldo, range = "A1",reformat = FALSE)



